/*
 * URx robot controller API docs
 *
 * API for the URx robot controller
 *
 * API version: 1.0.0
 * Contact: danai.vachtsevanou@unisg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Neighbor string

// List of Neighbor
const (
	0_ Neighbor = "0"
	1_ Neighbor = "1"
	ENGRAVER1 Neighbor = "engraver1"
	ENGRAVER2 Neighbor = "engraver2"
)
