/*
 * URx robot controller API docs
 *
 * API for the URx robot controller
 *
 * API version: 1.0.0
 * Contact: danai.vachtsevanou@unisg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Viewpoint struct {
	// The store towards which the viewpoint is positioned and oriented.
	Store int32 `json:"store,omitempty"`
	// The callback location passed to the robot controller. The robot controller will
	Callback string `json:"callback"`
}
