/*
 * URx robot controller API docs
 *
 * API for the URx robot controller
 *
 * API version: 1.0.0
 * Contact: danai.vachtsevanou@unisg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Coordinates struct {

	X float64 `json:"x"`

	Y float64 `json:"y"`

	Z float64 `json:"z"`
}
