/*
 * URx robot controller API docs
 *
 * API for the URx robot controller
 *
 * API version: 1.0.0
 * Contact: danai.vachtsevanou@unisg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GrabspotBody1 struct {

	Position *Neighbor `json:"position"`

	Callback string `json:"callback"`
}
