/*
 * URx robot controller API docs
 *
 * API for the URx robot controller
 *
 * API version: 1.0.0
 * Contact: danai.vachtsevanou@unisg.ch
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/danaivach/robot-controller/1.0.0/",
		Index,
	},

	Route{
		"GrabspotPut",
		strings.ToUpper("Put"),
		"/danaivach/robot-controller/1.0.0/grabspot",
		GrabspotPut,
	},

	Route{
		"OperatorGet",
		strings.ToUpper("Get"),
		"/danaivach/robot-controller/1.0.0/operator",
		OperatorGet,
	},

	Route{
		"OperatorPost",
		strings.ToUpper("Post"),
		"/danaivach/robot-controller/1.0.0/operator",
		OperatorPost,
	},

	Route{
		"OperatorTokenDelete",
		strings.ToUpper("Delete"),
		"/danaivach/robot-controller/1.0.0/operator/{token}",
		OperatorTokenDelete,
	},

	Route{
		"ReleasespotPut",
		strings.ToUpper("Put"),
		"/danaivach/robot-controller/1.0.0/releasespot",
		ReleasespotPut,
	},

	Route{
		"ViewpointPut",
		strings.ToUpper("Put"),
		"/danaivach/robot-controller/1.0.0/viewpoint",
		ViewpointPut,
	},
}
